name: "${project.name}"
main: "${project.groupId}.${project.artifactId}.${project.name}"
version: "${project.version}"
description: "${project.name} Bukkit Plugin"
author: "BillyGalbreath"
api-version: "1.13"

commands:
  pictures:
    description: Manage plugin
    permission: command.pictures
    usage: /<command> (reload | create)
    aliases:
      - picture

permissions:
  command.pictures:
    description: Allows to manage plugin
    default: op
